# Generated by Django 2.2.2 on 2019-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('developer_company', models.CharField(blank=True, max_length=255, null=True)),
                ('precessors', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
