# Generated by Django 2.2.2 on 2019-06-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='precessors',
            new_name='predescessors',
        ),
    ]
