# Generated by Django 2.2.2 on 2019-06-17 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190617_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
