# Generated by Django 2.2.2 on 2019-06-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_language_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='developer_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='predescessors',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
